### ISSUE TITLE
Async testing

### ISSUE THREAD

**Issue by munk** [yodle/smidje#4]
As a developer
I would like an abstraction over async tests
So I don't have to worry about channels in my tests, especially for mocked async functions

Acceptance criteria:
Tests should run inside a go block
They should check if something is a channel and read off it for the value

**Comment by munk** [comment]
This might be a helpful resource https://github.com/ams-clj/async-philosophers

**Comment by ragnorak1000** [comment]
closing for now since we don't have a use case yet or a real understanding of how we want to do this.
